name: Publish Tackle 2 Operator Images

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
jobs:
  build-operator-container:
    uses: jmontleon/actions/.github/workflows/publish-multi-arch-images.yml@main
    with:
      registry: quay.io
      image_name: ${{ github.repository }}-container
      dockerfile: Dockerfile
    secrets: inherit

  build-bundle-and-index:
    uses: jmontleon/actions/.github/workflows/publish-bundle-and-index.yml@main
    with:
      registry: quay.io
      bundle_image_name: ${{ github.repository }}-bundle
      bundle_dockerfile: bundle.Dockerfile
      index_image_name: ${{ github.repository }}-index
      supported_channels: ""
    secrets: inherit
