name: Set up minikube and deploy operator

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
jobs:
  install-minikube-and-tackle-operator:
    runs-on: ubuntu-latest
    steps:
    - name: Get minikube
      uses: JaydipGabani/tackle2-actions/get-minikube@main
    - name: Install tackle
      uses: JaydipGabani/tackle2-actions/install-tackle@main
